### ISSUE TITLE
Rename your release `3.0.0`

### ISSUE THREAD

**Issue by MrChocolatine** [briarsweetbriar/ember-get-config#22]
Rename [your release `3.0.0`](https://github.com/briarsweetbriar/ember-get-config/releases/tag/3.0.0), and its tag, to `v0.3.0`.

**Comment by mansona** [comment]
Yes I got confused by this too 😂  this should really be done since it's quite confusing for people

**Comment by mansona** [comment]
I just fixed this 👍
